### ISSUE TITLE
How sftp-tab supports multiple jump hosts

### ISSUE THREAD

**Issue by 0smboy** [wljince007/tabby-sftp-tab#1]

**Comment by wljince007** [comment]
No additional support is provided. The goal of this plugin is to supplement the functionality that Tabby lacks in opening the sftp tab compared to Securecrt, which meets my own needs. You can download this plugin, make modifications, submit a PR, and we will discuss whether to merge it into this plugin together.

**Comment by wljince007** [comment]
@0smboy  
1.0.7:
support multiple jump hosts, only support multiple jump hosts of type ProxyCommand and ProxyJump written in openssh-config files.
