### ISSUE TITLE
dows not open under mac osx

### ISSUE THREAD

**Issue by hxpq13** [wljince007/tabby-sftp-tab#2]
Installed openssh via brew and double checked path in mac profile but simply does not open at all

**Comment by wljince007** [comment]
Check if sftp is running normally.

```
/usr/local/opt/openssh/bin/sftp ***@****
```

and you can try relink openssh.

```
brew unlink openssh && brew link openssh
ls -la /usr/local/opt/openssh/bin/sftp
which sftp
```
